# Generated by Django 2.2.3 on 2019-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190730_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
