# Generated by Django 2.2.3 on 2019-07-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190730_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nick_name',
        ),
    ]
