# Generated by Django 2.2.3 on 2019-08-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_feebback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feebback',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
