# Generated by Django 2.2.3 on 2019-08-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_p_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_album',
            name='original_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
    ]
