# Generated by Django 2.2.3 on 2019-08-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_p_album_original_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_album',
            old_name='original_id',
            new_name='original',
        ),
    ]
